[package]
name = "measure_health_rs"
version = "0.1.0"
authors = ["gandalf.hudlow@gmail.com"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
array-init = "1.0.0"
lazy_static = "1.4.0"
rand = "0.7.3"
